name: Build NURBS Map Editor

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-msys2:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          make
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          mingw-w64-x86_64-glfw
          mingw-w64-x86_64-freeglut
          mingw-w64-x86_64-pkg-config
          
    - name: Build project
      shell: msys2 {0}
      run: |
        echo "Attempting CMake build..."
        mkdir -p build
        cd build
        cmake .. -G "MinGW Makefiles"
        make
    - name: Package binary
      shell: msys2 {0}
      run: |
        mkdir -p release

        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nurbs-map-editor-windows
        path: .
        retention-days: 30
