name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: [Debug, Release]

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          make
          mingw-w64-x86_64-make
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-gtk3
          mingw-w64-x86_64-glew
          mingw-w64-x86_64-freeglut

    - name: Build
      run: |
        if [ "${{ matrix.configuration }}" = "Debug" ]; then
          make debug
        else
          make release
        fi

    - name: Package
      if: matrix.configuration == 'Release'
      run: make package

    - name: Upload Artifacts
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: NurbsMapEditor-windows-x64
        path: build/package/*.zip

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config
        sudo apt-get install -y libgtk-3-dev libgl1-mesa-dev libglew-dev

    - name: Build
      run: make release

    - name: Package
      run: make package

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NurbsMapEditor-linux-x64
        path: build/package/*.tar.gz
