name: MSVC Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64]

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: '2024.01.12'

    - name: Install dependencies with vcpkg
      run: |
        vcpkg install gtk3:${{ matrix.platform }}-windows
        vcpkg install glew:${{ matrix.platform }}-windows
        vcpkg install opengl:${{ matrix.platform }}-windows
        vcpkg integrate install

    - name: Configure CMake
      run: |
        cmake -B build -S . -G "Visual Studio 17 2022" -A ${{ matrix.platform }} -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"

    - name: Build
      run: cmake --build build --config ${{ matrix.configuration }}

    - name: Test
      working-directory: build
      run: ctest -C ${{ matrix.configuration }} --output-on-failure

    - name: Package
      if: matrix.configuration == 'Release'
      run: |
        cmake --install build --config Release --prefix install
        7z a NurbsMapEditor-${{ matrix.platform }}-${{ github.sha }}.zip install/*

    - name: Upload Artifacts
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: NurbsMapEditor-${{ matrix.platform }}
        path: NurbsMapEditor-${{ matrix.platform }}-${{ github.sha }}.zip

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake pkg-config
        sudo apt-get install -y libgtk-3-dev libgl1-mesa-dev libglew-dev

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build

    - name: Package
      run: |
        cmake --install build --prefix install
        tar -czf NurbsMapEditor-linux-${{ github.sha }}.tar.gz install/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NurbsMapEditor-linux
        path: NurbsMapEditor-linux-${{ github.sha }}.tar.gz