name: MSVC Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/vcpkg
          ${{ github.workspace }}/vcpkg_installed
        key: ${{ runner.os }}-vcpkg-v2-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-v2-

    - name: Setup vcpkg
      run: |
        if (!(Test-Path "vcpkg")) {
          git clone https://github.com/Microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
        }
        .\vcpkg\vcpkg integrate install

    - name: Install dependencies with vcpkg
      run: |
        $env:VCPKG_DEFAULT_TRIPLET = "x64-windows"
        .\vcpkg\vcpkg install

    - name: Configure CMake
      run: |
        cmake -B build -S . -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"

    - name: Build
      run: cmake --build build --config ${{ matrix.configuration }}

    - name: Test
      working-directory: build
      run: ctest -C ${{ matrix.configuration }} --output-on-failure
      continue-on-error: true

    - name: Package
      if: matrix.configuration == 'Release'
      run: |
        cmake --install build --config Release --prefix install
        Compress-Archive -Path install/* -DestinationPath NurbsMapEditor-x64-${{ github.sha }}.zip

    - name: Upload Artifacts
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: NurbsMapEditor-x64
        path: NurbsMapEditor-x64-${{ github.sha }}.zip

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake pkg-config
        sudo apt-get install -y libgtk-3-dev libgl1-mesa-dev libglew-dev

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build

    - name: Test
      working-directory: build
      run: ctest --output-on-failure
      continue-on-error: true

    - name: Package
      run: |
        cmake --install build --prefix install
        tar -czf NurbsMapEditor-linux-x64-${{ github.sha }}.tar.gz install/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NurbsMapEditor-linux-x64
        path: NurbsMapEditor-linux-x64-${{ github.sha }}.tar.gz