name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: [Debug, Release]

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-gtk3
          mingw-w64-x86_64-glew
          mingw-w64-x86_64-freeglut

    - name: Configure CMake
      run: |
        cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

    - name: Build
      run: cmake --build build

    - name: Package
      if: matrix.configuration == 'Release'
      run: |
        cmake --install build --prefix install
        tar -czf NurbsMapEditor-windows-x64-${{ github.sha }}.tar.gz install/

    - name: Upload Artifacts
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: NurbsMapEditor-windows-x64
        path: NurbsMapEditor-windows-x64-${{ github.sha }}.tar.gz

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake pkg-config
        sudo apt-get install -y libgtk-3-dev libgl1-mesa-dev libglew-dev

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build

    - name: Package
      run: |
        cmake --install build --prefix install
        tar -czf NurbsMapEditor-linux-x64-${{ github.sha }}.tar.gz install/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NurbsMapEditor-linux-x64
        path: NurbsMapEditor-linux-x64-${{ github.sha }}.tar.gz